import type { NextPage } from 'next';
import Head from 'next/head';

import { BookMarkList } from 'containers';
import { ToolLayout } from 'components';

const CollectionsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToolLayout>
        <BookMarkList />
      </ToolLayout>
    </>
  );
};

export default CollectionsPage;
