import type { NextPage } from 'next'
import Head from 'next/head'

import { SideBar } from 'containers'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Deploy test
        </h1>
        <SideBar/>
      </main>
    </>      
  )
}

export default Home
