import type { NextPage } from 'next';
import Head from 'next/head';

import { Input, FolderIcon } from 'ui';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <aside className="h-screen w-80 bg-neutral-900">
          <header className="p-3">
            <span>dongqui9</span>
          </header>
          <ul>
            <li className="flex cursor-pointer items-center justify-between px-4 py-1 hover:bg-neutral-800">
              <div className="flex items-center justify-between">
                <FolderIcon />
                <span className="ml-2">모든 북마크</span>
              </div>
              <span className="mr-2 text-zinc-500">3</span>
            </li>

            <li className="flex cursor-pointer items-center justify-between px-4 py-1 hover:bg-neutral-800">
              <div className="flex items-center justify-between">
                <FolderIcon />
                <span className="ml-2">미분류</span>
              </div>
              <span className="mr-2 text-zinc-500">3</span>
            </li>
          </ul>
          <h3 className="px-4 py-3">컬렉션</h3>
        </aside>
        <div className="flex-1 bg-neutral-800"></div>
      </main>
    </>
  );
};

export default Home;
